services:
  - type: web
    name: todoapp-backend
    env: node
    plan: free
    buildCommand: npm ci
    startCommand: npm start
    envVars:
      - key: SESSION_SECRET
        sync: false
      - key: CORS_ORIGINS
        sync: false
      - key: ADMIN_USER
        sync: false
      - key: ADMIN_PASS_HASH
        sync: false
