version: "3.9"
services:
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todoapproll
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data